import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {latestFindings,prospectRatings,validateFindings,validateProspect,approvalRoute} from '../site/prospect-model.js';
import {validateActivity,parseBackup,today} from '../site/tracker-store.js';
import {validateResearch} from '../site/research-model.js';
import {mailingCategories,selectRecipients,defaultFilters,mergeMailingCatalog} from '../site/mailing-model.js';
const catalog=JSON.parse(await readFile(new URL('../site/data/mailing.json',import.meta.url),'utf8')).recipients;
const bice=catalog.find(r=>r.name==='Bice Law - Fort Mill');
const activity=(extra={})=>({id:'finding-1',companyId:bice.id,companyName:bice.name,contactId:null,contactName:'',recipient:'Office manager',type:'call',delivery:'',occurredOn:'2026-09-01',material:'',notes:'',outcome:'',followUpOn:'',followUpDone:false,createdAt:'2026-09-01T12:00:00Z',updatedAt:'2026-09-01T12:00:00Z',deletedAt:null,...extra});
test('rating exports stop when private findings cannot load',async({page},info)=>{
 test.skip(info.project.name!=='desktop','Storage failure runs once.');
 await page.addInitScript(()=>{const open=IDBFactory.prototype.open;IDBFactory.prototype.open=function(name,...args){if(name==='spray-net-partner-outreach')throw Error('Tracker unavailable');return open.call(this,name,...args)}});
 await page.goto('./#mailing?recipient='+bice.id);
 await page.locator('#mail-rating-access').selectOption('unknown');
 await expect(page.locator('#mail-count')).toContainText('Firsthand history is unavailable');
 await expect(page.locator('#mail-xlsx')).toBeDisabled();
});
test('findings resolve independently by actual contact date, ignore removed entries, and preserve old backups',async({},info)=>{
 test.skip(info.project.name!=='desktop','Pure model checks run once.');
 const old=activity({findings:{access:'tenant',opportunity:'high',reason:'Manager explained landlord approval; visible peeling on suitable siding.'}});
 const recent=activity({id:'finding-2',occurredOn:'2026-09-05',updatedAt:'2026-09-05T12:00:00Z',findings:{visit:'appointment',reason:'Office manager requested appointments.'}});
 const editedOld={...old,updatedAt:'2026-09-20T12:00:00Z'};
 expect(latestFindings([recent,editedOld],bice.id).access.value).toBe('tenant');
 expect(latestFindings([recent,editedOld],bice.id).visit.value).toBe('appointment');
 const unknown=activity({id:'finding-3',occurredOn:'2026-09-06',findings:{access:'unknown',reason:'New manager could not confirm the prior arrangement.'}});
 expect(approvalRoute(bice,latestFindings([old,unknown],bice.id))).toBe('unknown');
 expect(latestFindings([old,{...unknown,deletedAt:today()}],bice.id).access.value).toBe('tenant');
 const noEvidence={...bice,prospect:undefined,property:undefined};
 expect(prospectRatings(noEvidence).opportunity.value).toBe('unknown');
 expect(()=>validateFindings({access:'tenant',reason:''})).toThrow();
 expect(()=>validateFindings({access:'invented',reason:'bad'})).toThrow();
 expect(()=>validateProspect({evidence:{value:'direct',reason:'Public record is not firsthand.',source:'https://example.com',reviewedOn:today()}})).toThrow();
 const records=[activity(),old,recent].map((r,i)=>({...r,id:'backup-'+i}));
 records.forEach(validateActivity);
 expect(parseBackup(JSON.stringify({format:'spray-net-outreach',version:1,activities:records}))).toEqual(records);
 const filters={...defaultFilters(),categories:['professional'],access:'tenant'};
 expect(selectRecipients([bice],filters,[],()=>null,today(),id=>latestFindings([old],id)).rows).toHaveLength(1);
 expect(selectRecipients([bice],filters,[],()=>null,today()).rows).toHaveLength(0);
 const inherited=mergeMailingCatalog([],[{id:5,name:'Reviewed office',category:'professional',visit:{status:'appointment_only',summary:'Appointments required by the office.',checkedAt:today(),sources:['https://example.com/contact']}}]);
 expect(prospectRatings(inherited[0]).visit.value).toBe('appointment');
 expect(prospectRatings(inherited[0],{visit:{value:'home_based',reason:'Moved',reviewedOn:today(),firsthand:true}}).visit.value).toBe('home_based');
});
test('research log distinguishes checked sources, unresolved leads and queued areas',async({page})=>{
 await page.goto('./#mailing');
 await page.locator('#mail-coverage > summary').click();
 await page.locator('#coverage-category').selectOption('professional');
 const fort=page.locator('[data-coverage-area="fort_mill"]');
 await expect(fort).toContainText('Sources checked 2026-09-22');
 await fort.getByText('Source history (1 pass)',{exact:true}).click();
 await expect(fort).toContainText('Nantz');
 await expect(fort).toContainText('not an exhaustive');
 await expect(page.locator('[data-coverage-area="marvin"]')).toContainText('no source pass logged');
 await page.locator('#coverage-status').selectOption('unsearched');
 await expect(fort).toHaveCount(0);
 await expect(page.locator('[data-coverage-area="marvin"]')).toBeVisible();
 const log=JSON.parse(await readFile(new URL('../site/data/research.json',import.meta.url),'utf8'));
 expect(()=>validateResearch(log,catalog,mailingCategories)).not.toThrow();
 const bad=structuredClone(log);bad.passes[0].reviewedIds=[999999999];expect(()=>validateResearch(bad,catalog,mailingCategories)).toThrow();
});
test('a firsthand home-office finding removes a public drop-in stop and its directions',async({page})=>{
 await page.goto('./#directory?city=Fort+Mill&visit=walk_in');
 await page.getByRole('link',{name:'Baxter Cabinets - Fort Mill Showroom',exact:true}).click();
 await expect(page.getByRole('link',{name:'Directions to visitor address'})).toBeVisible();
 await page.locator('#profile .log-details > summary').click();
 const form=page.locator('#profile .activity-form');
 await form.locator('[name=type]').selectOption('call');
 await form.locator('.finding-fields > summary').click();
 await form.locator('[name=finding_visit]').selectOption('home_based');
 await form.locator('[name=finding_reason]').fill('Test finding: manager says the visitor office moved to a home office.');
 await form.getByRole('button',{name:'Save activity',exact:true}).click();
 await expect(form.locator('.form-message')).toContainText('Activity saved');
 await expect(page.locator('.visit-panel')).toContainText('Home-based');
 await expect(page.getByRole('link',{name:'Directions to visitor address'})).toHaveCount(0);
 await page.getByRole('button',{name:'Back to directory'}).click();
 await expect(page.locator('#cards')).not.toContainText('Baxter Cabinets');
 await page.locator('#visit').selectOption('home_based');
 await expect(page.locator('#cards')).toContainText('Baxter Cabinets');
});
test('firsthand findings override mailing ratings, survive reload and backup, and revert after removal',async({page,context,browserName,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('./#mailing?recipient='+bice.id);
 const card=page.locator(`#mail-rows [data-recipient="${bice.id}"]`);
 await card.getByRole('link',{name:'Log activity / firsthand finding'}).click();
 await expect(page.locator('#tracker')).toBeVisible();
 const form=page.locator('#tracker .activity-form');
 await page.locator('#tracker .log-details > summary').click();
 await expect(form.locator('[name=companyId]')).toHaveValue(String(bice.id));
 await form.locator('[name=type]').selectOption('call');
 await form.locator('.finding-fields > summary').click();
 await form.locator('[name=finding_access]').selectOption('tenant');
 await form.locator('[name=finding_visit]').selectOption('appointment');
 await form.locator('[name=finding_reason]').fill('Office manager confirmed landlord approval and requested a scheduled introduction.');
 await form.getByRole('button',{name:'Save activity',exact:true}).click();
 await expect(form.locator('.form-message')).toContainText('Activity saved');
 await expect(page.locator('#tracker .firsthand-finding')).toContainText('Tenant');
 const downloadPromise=page.waitForEvent('download');await page.locator('#backup-export').click();
 const file=await downloadPromise,b=JSON.parse(await readFile(await file.path(),'utf8'));
 expect(b.activities[0].findings.access).toBe('tenant');
 const second=await browser.newContext({baseURL:'http://127.0.0.1:4174/spray-net-network-pwa/'});
 try{
  const restored=await second.newPage();await restored.goto('./#tracker');
  await restored.locator('#backup-import').setInputFiles({name:'findings.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(b))});
  await restored.getByRole('button',{name:'Merge backup',exact:true}).click();
  await expect(restored.locator('#backup-status')).toContainText('Imported 1');
  await restored.goto('./#mailing?recipient='+bice.id);await restored.locator('#mail-rating-access').selectOption('tenant');
  await expect(restored.locator(`#mail-rows [data-recipient="${bice.id}"]`)).toBeVisible();
 }finally{await second.close()}
 await page.goto('./#mailing?recipient='+bice.id);
 await page.locator('#mail-rating-access').selectOption('tenant');
 await expect(card).toBeVisible();
 await card.locator('.prospect-ratings > summary').click();
 await expect(card).toContainText('Your firsthand finding');
 await expect(card).toContainText('Firsthand information applies only');
 await page.getByLabel('List name',{exact:true}).fill('Confirmed tenant follow-up');await page.locator('#mail-save').click();
 await expect(page.locator('#mailing-status')).toContainText('saved');
 await expect(page.locator('#connection')).toHaveText('Ready offline');
 if(browserName!=='webkit')await context.setOffline(true);
 await page.reload();await page.locator('#mail-saved').selectOption('Confirmed tenant follow-up');
 await expect(page.locator('#mail-rating-access')).toHaveValue('tenant');await expect(card).toBeVisible();
 await context.setOffline(false);
 await card.getByRole('link',{name:'Log activity / firsthand finding'}).click();
 await page.locator('#tracker .activity-entry').getByRole('button',{name:'Remove',exact:true}).click();
 await page.goto('./#mailing?recipient='+bice.id);
 await page.locator('#mail-rating-access').selectOption('tenant');
 await expect(card).toHaveCount(0);
 expect(errors).toEqual([]);
});
