import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const ben='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
await db.exec((await readFile('supabase/team-sync.sql','utf8')).replaceAll('replace-with-your-login@example.com','owner@example.test'));
await db.exec(`insert into auth.users values('${ben}','owner@example.test',now()),('${other}','not-approved@example.test',now());set role authenticated;select set_config('request.jwt.claim.sub','${other}',false);`);
await assert.rejects(()=>db.query('select public.network_pull()'),/not approved/);
await db.exec(`select set_config('request.jwt.claim.sub','${ben}',false);`);
assert.equal((await db.query('select public.network_pull() as data')).rows[0].data.records.length,0);
const commit=async(id,changes)=>(await db.query('select public.network_commit($1::uuid,$2::jsonb) as data',[id,JSON.stringify(changes)])).rows[0].data;
const row={kind:'social',key:'test',expected:0,payload:{status:'followed'}};
await commit('33333333-3333-4333-8333-333333333333',[row]);
const twice=await commit('33333333-3333-4333-8333-333333333333',[row]);assert.equal(twice.records[0].revision,1);assert.equal(twice.records[0].updated_by,ben);
await assert.rejects(()=>commit('44444444-4444-4444-8444-444444444444',[{...row,key:'should-rollback'},row]),/SYNC_CONFLICT/);
assert.equal((await db.query('select public.network_pull() as data')).rows[0].data.records.length,1);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query('select * from public.network_records')).rows.length,0);
await assert.rejects(()=>commit('55555555-5555-4555-8555-555555555555',[row]),/not approved/);
await assert.rejects(()=>db.exec(`insert into public.network_members values('${other}','Sneaky',true)`),/permission denied/);
await db.exec(`reset role;update public.network_members set active=false where user_id='${ben}';set role authenticated;select set_config('request.jwt.claim.sub','${ben}',false);`);
await assert.rejects(()=>db.query('select public.network_pull()'),/not approved/);
await db.exec('reset role;set role anon;');await assert.rejects(()=>db.query('select public.network_pull()'),/permission denied/);
await db.close();console.log('SQL checks passed: access isolation, member enrollment, revocation, atomic conflicts, actor stamps, idempotent retry.');
